// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using UtilityDelta.EFCore.Database;

namespace UtilityDelta.EFCore.Database.Migrations
{
    [DbContext(typeof(FamilyContext))]
    [Migration("20170817055656_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("UtilityDelta.EFCore.Entities.Grandparent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Grandparents");
                });

            modelBuilder.Entity("UtilityDelta.EFCore.Entities.Kid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsCool");

                    b.Property<string>("Name");

                    b.Property<int>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Kids");
                });

            modelBuilder.Entity("UtilityDelta.EFCore.Entities.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GrandparentId");

                    b.Property<bool>("IsMale");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GrandparentId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("UtilityDelta.EFCore.Entities.Kid", b =>
                {
                    b.HasOne("UtilityDelta.EFCore.Entities.Parent", "Parent")
                        .WithMany("Kids")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("UtilityDelta.EFCore.Entities.Parent", b =>
                {
                    b.HasOne("UtilityDelta.EFCore.Entities.Grandparent", "Grandparent")
                        .WithMany("Parents")
                        .HasForeignKey("GrandparentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
